---
- name: Setting sysctl values
  become: true
  sysctl: name={{ item.name }} value={{ item.value }} sysctl_set=yes
  with_items:
    - { name: "net.ipv4.ip_forward", value: 1}
    - { name: "net.ipv4.conf.all.rp_filter", value: 0}
    - { name: "net.ipv4.conf.default.rp_filter", value: 0}
  when:
    - set_sysctl | bool

- name: Ensuring config directories exist
  become: true
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: "directory"
    mode: "0770"
  when:
    - item.value.enabled | bool
    - item.value.host_in_groups | bool
  with_dict: "{{ neutron_services }}"

- name: Check if extra ml2 plugins exists
  local_action: find path="{{ node_custom_config }}/neutron/plugins/"
  run_once: True
  changed_when: False
  register: check_extra_ml2_plugins

- name: Copying over config.json files for services
  become: true
  template:
    src: "{{ item.key }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/config.json"
    mode: "0770"
  register: neutron_config_jsons
  when:
    - item.value.enabled | bool
    - item.value.host_in_groups | bool
  with_dict: "{{ neutron_services }}"
  notify:
    - "Restart {{ item.key }} container"

- name: Copying over neutron.conf
  become: true
  vars:
    service_name: "{{ item.key }}"
    services_need_neutron_conf:
      - "neutron-server"
      - "neutron-zvm-agent"
  merge_configs:
    sources:
      - "{{ role_path }}/templates/neutron.conf.j2"
      - "{{ node_custom_config }}/global.conf"
      - "{{ node_custom_config }}/neutron.conf"
      - "{{ node_custom_config }}/neutron/{{ item.key }}.conf"
      - "{{ node_custom_config }}/neutron/{{ inventory_hostname }}/neutron.conf"
    dest: "{{ node_config_directory }}/{{ item.key }}/neutron.conf"
    mode: "0660"
  register: neutron_confs
  when:
    - item.value.enabled | bool
    - item.value.host_in_groups | bool
    - item.key in services_need_neutron_conf
  with_dict: "{{ neutron_services }}"
  notify:
    - "Restart {{ item.key }} container"

- name: Copying over neutron_zvm_plugin.ini
  become: true
  vars:
    service_name: "{{ item.key }}"
    services_need_neutron_zvm_plugin_ini:
      - "neutron-zvm-agent"
  merge_configs:
    sources:
      - "{{ role_path }}/templates/neutron_zvm_plugin.ini.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/neutron_zvm_plugin.ini"
  register: neutron_zvm_plugin_inis
  when:
    - item.value.enabled | bool
    - item.value.host_in_groups | bool
    - item.key in services_need_neutron_zvm_plugin_ini
  with_dict: "{{ neutron_services }}"
  notify:
    - "Restart {{ item.key }} container"

- name: Copying over ml2_conf.ini
  become: true
  vars:
    service_name: "{{ item.key }}"
    services_need_ml2_conf_ini:
      - "neutron-server"
      - "neutron-zvm-agent"
  merge_configs:
    sources:
      - "{{ role_path }}/templates/ml2_conf.ini.j2"
      - "{{ node_custom_config }}/neutron/ml2_conf.ini"
      - "{{ node_custom_config }}/neutron/{{ inventory_hostname }}/ml2_conf.ini"
    dest: "{{ node_config_directory }}/{{ service_name }}/ml2_conf.ini"
    mode: "0660"
  register: neutron_ml2_confs
  when:
    - item.key in services_need_ml2_conf_ini
    - item.value.enabled | bool
    - item.value.host_in_groups | bool
  with_dict: "{{ neutron_services }}"
  notify:
    - "Restart {{ item.key }} container"

- name: Check if policies shall be overwritten
  local_action: stat path="{{ node_custom_config }}/neutron/policy.json"
  run_once: True
  register: neutron_policy

- name: Copying over existing policy.json
  become: true
  vars:
    service_name: "{{ item.key }}"
    services_need_policy_json:
      - "neutron-server"
      - "neutron-zvm-agent"
  template:
    src: "{{ node_custom_config }}/neutron/policy.json"
    dest: "{{ node_config_directory }}/{{ service_name }}/policy.json"
    mode: "0660"
  register: policy_jsons
  when:
    - neutron_policy.stat.exists
    - item.value.enabled | bool
    - item.value.host_in_groups | bool
  with_dict: "{{ neutron_services }}"
  notify:
    - "Restart {{ item.key }} container"

- name: Copying over extra ml2 plugins
  become: true
  vars:
    service_name: "{{ item.0 }}"
    services_need_ml2_conf_ini:
      - "neutron-server"
      - "neutron-zvm-agent"
  template:
    src: "{{ item.2.path }}"
    dest: "{{ node_config_directory }}/{{ service_name }}/{{ item.2.path | basename }}"
    mode: "0660"
  register: extra_ml2_plugins
  when:
    - item.2 is defined
    - item.1.enabled | bool
    - item.1.host_in_groups | bool
    - service_name in services_need_ml2_conf_ini
  with_nested:
    - "{{ neutron_services | dictsort }}"
    - "{{ check_extra_ml2_plugins.files }}"
  notify:
    - "Restart {{ item.0 }} container"

# TODO check the environment change
- name: Check neutron containers
  kolla_docker:
    action: "compare_container"
    common_options: "{{ docker_common_options }}"
    name: "{{ item.value.container_name }}"
    image: "{{ item.value.image }}"
    privileged: "{{ item.value.privileged | default(False) }}"
    volumes: "{{ item.value.volumes }}"
  register: check_neutron_containers
  when:
    - action != "config"
    - item.value.enabled | bool
    - item.value.host_in_groups | bool
  with_dict: "{{ neutron_services }}"
  notify:
    - "Restart {{ item.key }} container"
